# Generated by Django 5.1.5 on 2025-06-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoprice',
            options={},
        ),
        migrations.RemoveField(
            model_name='investmenttier',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='investmenttier',
            name='duration_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='investmenttier',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PROFESSIONAL', 'Professional'), ('ADVANCED', 'Advanced')], max_length=20, unique=True),
        ),
    ]
