# Generated by Django 5.1.4 on 2025-06-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_alter_cryptoprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttier',
            name='capital_return',
            field=models.BooleanField(default=True),
        ),
    ]
